### ISSUE TITLE
배포 인스턴스 변경

### ISSUE THREAD

**Issue by orijoon98** [Photory-Official/photory-server#63]
## 📌  Feature Issue

배포 관련 수정

## 📝  To-do

- [x] 배포 인스턴스 변경
- [x] CI/CD 수정
- [x] 배포 데이터베이스 AWS RDS, Elastic Cache 로 변경
